# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: Cursos
    weight: 20
    identifier: courses
  - name: Español Moderno II
    PageRef: course/data-science/_index.md
    weight: 10
    parent: courses
  - name: Libro de Lectura II
    PageRef: course/robotics/_index.md
    weight: 20
    parent: courses
  # - name: Blog
  #  PageRef: post/_index.md
  #  weight: 30
  - name: Contact
    PageRef: contact/index.md
    weight: 60
